from PyQt6.QtWidgets import QWidget, QLayout, QHBoxLayout, QLabel, QFormLayout


class PersonalInfoWidget(QWidget):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setObjectName("personalInfoWidget")
        self.setLayout(self.create_gui())

    def create_gui(self) -> QLayout:
        main_layout = QHBoxLayout()
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(5)
        self.contact_photo_label = QLabel()
        self.contact_photo_label.setObjectName("contactPhotoLabel")
        self.contact_photo_label.setFixedSize(150, 150)
        main_info_layout = QFormLayout()
        main_info_layout.setContentsMargins(0, 0, 0, 0)
        main_info_layout.setSpacing(5)
        self.contact_title_text_label = QLabel("Title:")
        self.contact_title_text_label.setObjectName("contactTitleTextLabel")
        self.contact_title_label = QLabel("ing")
        self.contact_title_label.setObjectName("contactTitleLabel")
        self.contact_first_name_text_label = QLabel("first name:")
        self.contact_first_name_text_label.setObjectName("contactFirstNameTextLabel")
        self.contact_first_name_label = QLabel("fisrt name")
        self.contact_first_name_label.setObjectName("contactFirstNameLabel")
        self.contact_second_name_text_label = QLabel("second name:")
        self.contact_second_name_text_label.setObjectName("contactSecondNameTextLabel")
        self.contact_second_name_label = QLabel("second name")
        self.contact_second_name_label.setObjectName("contactSecondNameLabel")
        self.contact_relationship_text_label = QLabel("relatiton:")
        self.contact_relationship_text_label.setObjectName("contactRelationshipTextLabel")
        self.contact_relationship_label = QLabel("family")
        self.contact_relationship_label.setObjectName("contactRelationshipLabel")
        self.contact_birthday_text_label = QLabel("birthday:")
        self.contact_birthday_text_label.setObjectName("contactBirthdayTextLabel")
        self.contact_birthday_label = QLabel("1.1.2025")
        self.contact_birthday_label.setObjectName("contactBirthdayLabel")
        main_info_layout.addRow(self.contact_title_text_label, self.contact_title_label)
        main_info_layout.addRow(self.contact_first_name_text_label, self.contact_first_name_label)
        main_info_layout.addRow(self.contact_second_name_text_label, self.contact_second_name_label)
        main_info_layout.addRow(self.contact_relationship_text_label, self.contact_relationship_label)
        main_info_layout.addRow(self.contact_birthday_text_label, self.contact_birthday_label)
        main_layout.addWidget(self.contact_photo_label)
        main_layout.addLayout(main_info_layout)
        main_layout.addStretch()
        return main_layout