from PyQt6.QtCore import QSize
from PyQt6.QtWidgets import QTabWidget, QWidget, QHBoxLayout, QVBoxLayout, QPushButton, QLabel, QFormLayout


class TabInfoWidget(QTabWidget):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setObjectName("tabInfoWidget")
        self.setFixedHeight(250)
        self.setContentsMargins(0, 0, 0, 0)
        self.buttons_size = QSize(35, 35)
        self.personal_tab_text = "Personal"
        self.work_tab_text = "Work"
        self.addTab(self.create_personal_tab(), self.personal_tab_text)
        self.addTab(self.create_work_tab(), self.work_tab_text)

    def create_personal_tab(self) -> QWidget:
        personal_widget = QWidget()
        personal_layout = QVBoxLayout()
        personal_social_network_layout = QHBoxLayout()
        self.facebook_pushbutton = QPushButton("fb")
        self.facebook_pushbutton.setObjectName("facebookPushbutton")
        self.facebook_pushbutton.setFixedSize(self.buttons_size)
        self.x_pushbutton = QPushButton("x")
        self.x_pushbutton.setObjectName("xPushbutton")
        self.x_pushbutton.setFixedSize(self.buttons_size)
        self.instagram_pushbutton = QPushButton("ig")
        self.instagram_pushbutton.setObjectName("instagramPushbutton")
        self.instagram_pushbutton.setFixedSize(self.buttons_size)
        personal_social_network_layout.addWidget(self.facebook_pushbutton)
        personal_social_network_layout.addWidget(self.x_pushbutton)
        personal_social_network_layout.addWidget(self.instagram_pushbutton)
        personal_social_network_layout.addStretch()
        personal_contact_layout = QFormLayout()
        self.personal_email_text_label = QLabel("email:")
        self.personal_email_text_label.setObjectName("personalEmailTextLabel")
        self.personal_email_label = QLabel("personal@email.com")
        self.personal_email_label.setObjectName("personalEmailLabel")
        self.personal_phone_number_text_label = QLabel("phone:")
        self.personal_phone_number_text_label.setObjectName("personalPhoneNumberTextLabel")
        self.personal_phone_number_label = QLabel("123456789")
        self.personal_phone_number_label.setObjectName("personalPhoneNumberLabel")
        self.personal_address_text_label = QLabel("Address:")
        self.personal_address_text_label.setObjectName("personalAddressTextLabel")
        self.personal_address_label = QLabel("personal home 123")
        self.personal_address_label.setObjectName("personalAddressLabel")
        self.personal_city_text_label = QLabel("city:")
        self.personal_city_text_label.setObjectName("personalCityTextLabel")
        self.personal_city_label = QLabel("personal city")
        self.personal_city_label.setObjectName("personalCityLabel")
        self.personal_post_code_text_label = QLabel("post code:")
        self.personal_post_code_text_label.setObjectName("personalPostCodeTextLabel")
        self.personal_post_code_label = QLabel("12345")
        self.personal_post_code_label.setObjectName("personalPostCodeLabel")
        self.personal_country_text_label = QLabel("country:")
        self.personal_country_text_label.setObjectName("personalCountryTextLabel")
        self.personal_country_label = QLabel("personal country")
        self.personal_country_label.setObjectName("personalCountryLabel")
        personal_contact_layout.addRow(self.personal_email_text_label, self.personal_email_label)
        personal_contact_layout.addRow(self.personal_phone_number_text_label, self.personal_phone_number_label)
        personal_contact_layout.addRow(self.personal_address_text_label, self.personal_address_label)
        personal_contact_layout.addRow(self.personal_city_text_label, self.personal_city_label)
        personal_contact_layout.addRow(self.personal_post_code_text_label, self.personal_post_code_label)
        personal_contact_layout.addRow(self.personal_country_text_label, self.personal_country_label)
        personal_layout.addLayout(personal_social_network_layout)
        personal_layout.addLayout(personal_contact_layout)
        personal_layout.addStretch()
        personal_widget.setLayout(personal_layout)
        return personal_widget

    def create_work_tab(self) -> QWidget:
        work_widget = QWidget()
        work_layout = QVBoxLayout()
        work_social_network_layout = QHBoxLayout()
        self.lindedln_pushbutton = QPushButton("ld")
        self.lindedln_pushbutton.setObjectName("lindedlnPushbutton")
        self.lindedln_pushbutton.setFixedSize(self.buttons_size)
        self.github_pushbutton = QPushButton("gh")
        self.github_pushbutton.setObjectName("githubPushbutton")
        self.github_pushbutton.setFixedSize(self.buttons_size)
        self.work_website_pushbutton = QPushButton("ws")
        self.work_website_pushbutton.setObjectName("workWebsitePushbutton")
        self.work_website_pushbutton.setFixedSize(self.buttons_size)
        work_social_network_layout.addWidget(self.lindedln_pushbutton)
        work_social_network_layout.addWidget(self.github_pushbutton)
        work_social_network_layout.addWidget(self.work_website_pushbutton)
        work_social_network_layout.addStretch()
        work_contact_layout = QFormLayout()
        self.work_email_text_label = QLabel("email:")
        self.work_email_text_label.setObjectName("workEmailTextLabel")
        self.work_email_label = QLabel("work@email.com")
        self.work_email_label.setObjectName("workEmailLabel")
        self.work_phone_number_text_label = QLabel("phone:")
        self.work_phone_number_text_label.setObjectName("workPhoneNumberTextLabel")
        self.work_phone_number_label = QLabel("987654321")
        self.work_phone_number_label.setObjectName("workPhoneNumberLabel")
        self.work_address_text_label = QLabel("Address:")
        self.work_address_text_label.setObjectName("workAddressTextLabel")
        self.work_address_label = QLabel("work home 123")
        self.work_address_label.setObjectName("workAddressLabel")
        self.work_city_text_label = QLabel("city:")
        self.work_city_text_label.setObjectName("workCityTextLabel")
        self.work_city_label = QLabel("work city")
        self.work_city_label.setObjectName("workCityLabel")
        self.work_post_code_text_label = QLabel("post code:")
        self.work_post_code_text_label.setObjectName("workPostCodeTextLabel")
        self.work_post_code_label = QLabel("54321")
        self.work_post_code_label.setObjectName("workPostCodeLabel")
        self.work_country_text_label = QLabel("country:")
        self.work_country_text_label.setObjectName("workCountryTextLabel")
        self.work_country_label = QLabel("work country")
        self.work_country_label.setObjectName("workCountryLabel")
        work_contact_layout.addRow(self.work_email_text_label, self.work_email_label)
        work_contact_layout.addRow(self.work_phone_number_text_label, self.work_phone_number_label)
        work_contact_layout.addRow(self.work_address_text_label, self.work_address_label)
        work_contact_layout.addRow(self.work_city_text_label, self.work_city_label)
        work_contact_layout.addRow(self.work_post_code_text_label, self.work_post_code_label)
        work_contact_layout.addRow(self.work_country_text_label, self.work_country_label)
        work_layout.addLayout(work_social_network_layout)
        work_layout.addLayout(work_contact_layout)
        work_layout.addStretch()
        work_widget.setLayout(work_layout)
        return work_widget